import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/landing/navbar";
import { fonts } from "@/lib/fonts";
import Providers from "@/components/global/providers";
import Footer from "@/components/landing/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={fonts}>
        <Providers attribute="class" defaultTheme="light" disableTransitionOnChange>
         <Navbar/>
         {children}
         <Footer/>
        </Providers>
      </body>
    </html>
  );
}
